# Generated by Django 5.2.7 on 2026-05-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_text_message_content_remove_message_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.CharField(max_length=100),
        ),
    ]
