# Generated by Django 5.2.7 on 2026-05-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_typingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingstatus',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
