
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS nakshatram TEXT,
  ADD COLUMN IF NOT EXISTS rasi TEXT,
  ADD COLUMN IF NOT EXISTS thidi TEXT,
  ADD COLUMN IF NOT EXISTS gothram TEXT,
  ADD COLUMN IF NOT EXISTS manglik TEXT,
  ADD COLUMN IF NOT EXISTS time_of_birth TIME,
  ADD COLUMN IF NOT EXISTS place_of_birth TEXT,
  ADD COLUMN IF NOT EXISTS diet TEXT,
  ADD COLUMN IF NOT EXISTS body_type TEXT,
  ADD COLUMN IF NOT EXISTS complexion TEXT,
  ADD COLUMN IF NOT EXISTS blood_group TEXT,
  ADD COLUMN IF NOT EXISTS contact_phone TEXT;
